{
    "name": "CarePulse",
    "version": "19.0.1.0.0",
    "category": "Services",
    "summary": "Clinic management: visit to paid invoice",
    "author": "Samy Mostafa Shaawat",
    "license": "OEEL-1",
    "depends": [
        "base",
        "mail",
        "website",
        "contacts",
        "crm",
        "calendar",
        "sale_management",
        "account",
        "stock",
        "hr",
        "hr_attendance",
        "website_enterprise",
    ],
    "data": [
        "security/security.xml",
        "security/ir.model.access.csv",
        "data/data.xml",
        "views/menus.xml",
    ],
    "demo": [
        "demo/demo.xml",
    ],
    "installable": True,
    "application": True,
}
